description: "Welcome to the home of the ultrapod project. The ultrapod project's aim is to provide accessible, biologically clean water to diverse populations around the world, through the use of the ultrapod, a device that is currently in the prototyping phase."
keywords: - innovation
 - clean 
 - water
 - device
 - ultrapod
 - ultraviolet
 - purification
 - team
 - cheap
 - conrad
 - awards
markdown: rdiscount
